### ISSUE TITLE
HttpResponse Class

### ISSUE THREAD

**Issue by mengdilin** [mengdilin/Cjango-Unchained#2]
# HttpResponse Design
## member variables
* string content: a raw string representing the body of the http response
* int status_code: the status of a http response
* string reason_phrase: the reason for the current status
   * ex: "200 OK"
* static const code_to_reason map: populated with status code and reason_phrase pairs once
* string content-type: type of the content

## member functions
* HttpResponse(String) constructor where string is the body of the http response
* HttpResponse(String body, String content_type) constructor
   * HttpResponse response = HttpResponse("Text only, please.", "text/plain");
* write(String) allows HttpResponse to be populated incrementally.
   * Example: 
     ```
     HttpResponse response = HttpResponse();
     response.write("<p>Here's the text of the Web page.</p>");
     response.write("<p>Here's another paragraph.</p>");
     ```
## Second Phase
* HttpResponse cookie support
* HttpResponse session support
* support adding and removing of header fields
---
reference:
* ripped off API from Django: https://docs.djangoproject.com/en/1.10/ref/request-response/
* details on how http request is transmitted over the wire in text: https://www.tutorialspoint.com/http/http_requests.htm

**Comment by caprice-j** [comment]
Status code doesn't start from 0 like 001? All starts from non-zero?
