### ISSUE TITLE
Router class

### ISSUE THREAD

**Issue by mengdilin** [mengdilin/Cjango-Unchained#3]
# Router Class
## member variables
* pattern_to_callback: a map that given a url_path, returns a callback function corresponding to the url_pattern. 
* patterns_list: a vector of patterns, in the exact order of how the user registers the patterns.
   Example:
   ```
          Router.add("/abc", some call back);
          Router.add("/efg", some call back);
          Router.add("/xyz", some call back);
          //patterns_list should have the patterns in the order: ["/abc", "/efg", "/xyz"]
   ```
## member functions
* ```Router(map<string, functor> routes)```: constructor that calls ```add_route``` to populate pattern_to_callback and patterns_list.
* ```add_route(string url_pattern, functor callback)```: callback must have the signature ```HttpResponse f(HttpRequest)```. Given a ```url_pattern``` and a ```callback``` functor, we store this pair in ```pattern_to_callback``` member variable and update ```patterns_list```. We throw an error if we are trying to register the same ```url_pattern``` with different ```callback``` functors. Note, ```url_pattern``` may be a regex pattern or an actual url_path. 
* ```string resolve(HttpRequest)```: given a http request, it returns the url_pattern corresponding to the http request. Example: a request for "/abc/e" will return "/abc/e". ```resolve``` becomes more complicated if we allow regex resolution.
   * example: parameter: HttpRequest for url path "articles/14/12/"
                     patterns_list/pattern_to_callback have a url_pattern "articles/([0-9]{4})/([0-9]{2})/$"
                     return: the url_pattern
   Note that if there are 2 potential matching patterns for a given HttpRequest, we return the first matching pattern found in patterns_list.

* ```HttpResponse get_http_response(HttpRequest)```: given a http request, it returns the corresponding http response.
```
pseudo code:
HttpResponse get_http_response(HttpRequest request) {
    string url_path = resolve(request);
    functor callback = pattern_to_callback.find(url_path);
    return callback(request):
}
```
Note, have to handle casese if resolve cannot find any url_path, this would be a "404 Not Found" response. We perhaps will have helper functions for constructing these error responses.

**Comment by caprice-j** [comment]
Django uses Python's URLconf module: https://docs.djangoproject.com/ja/1.10/topics/http/urls/

**Comment by caprice-j** [comment]
I'll check later: 
http://www.django-rest-framework.org/api-guide/routers/

**Comment by caprice-j** [comment]
Now I've understood why django doesn't have Router class.
From the above documentation:

```
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'users', UserViewSet)
router.register(r'accounts', AccountViewSet)
urlpatterns = router.urls
```

or 
```
urlpatterns = [
    url(r'^forgot-password/$', ForgotPasswordFormView.as_view()),
]

urlpatterns += router.urls
```

In other words, the `routers` class defines a set of rules (`^users/$ -> 'user-list'` and `^users/{pk}/$ -> 'user-detail'`) by just `router.register(r'users', UserViewSet)`. The registered rules can be included in url matching rules (`urlpatterns`) like above. This implies users can use `routers` (our `Router` class?) directly to set URL patterns.

Since our foundational objective is to mimic django API, It's better for our Router class to follow this pattern. I'll post rewritten version of our Router class in the next post.

**Comment by caprice-j** [comment]
### Editting now

# Router Class
## member variables
* pattern_to_callback: a map that given a url_path, returns a callback function corresponding to the url_pattern. 
* patterns_list: a vector of patterns, in the exact order of how the user registers the patterns.
   Example:
   ```
          Router.add("/abc", some call back);
          Router.add("/efg", some call back);
          Router.add("/xyz", some call back);
          //patterns_list should have the patterns in the order: ["/abc", "/efg", "/xyz"]
   ```
## member functions
* ```Router(map<string, functor> routes)```: constructor that calls ```add_route``` to populate pattern_to_callback and patterns_list.
* ```add_route(string url_pattern, functor callback)```: callback must have the signature ```HttpResponse f(HttpRequest)```. Given a ```url_pattern``` and a ```callback``` functor, we store this pair in ```pattern_to_callback``` member variable and update ```patterns_list```. We throw an error if we are trying to register the same ```url_pattern``` with different ```callback``` functors. Note, ```url_pattern``` may be a regex pattern or an actual url_path. 
* ```string resolve(HttpRequest)```: given a http request, it returns the url_pattern corresponding to the http request. Example: a request for "/abc/e" will return "/abc/e". ```resolve``` becomes more complicated if we allow regex resolution.
   * example: parameter: HttpRequest for url path "articles/14/12/"
                     patterns_list/pattern_to_callback have a url_pattern "articles/([0-9]{4})/([0-9]{2})/$"
                     return: the url_pattern
   Note that if there are 2 potential matching patterns for a given HttpRequest, we return the first matching pattern found in patterns_list.

* ```HttpResponse get_http_response(HttpRequest)```: given a http request, it returns the corresponding http response.
```
pseudo code:
HttpResponse get_http_response(HttpRequest request) {
    string url_path = resolve(request);
    functor callback = pattern_to_callback.find(url_path);
    return callback(request):
}
```
Note, have to handle casese if resolve cannot find any url_path, this would be a "404 Not Found" response. We perhaps will have helper functions for constructing these error responses.

**Comment by mengdilin** [comment]
Like the new name change!  Let's not think about class hierarchies for the router for now since our router is simple enough, unless you think class hierarchy already makes sense in your implementation? In terms of view classes, I believe it is outside the scope of this project after reading about it on the django website. It has supports for things such as redirect, finer-grained of control in terms of what to pass in http response header, and templating. I like the idea of redirect (something we should consider adding to our project), but I don't think we need the full-blown view class.

**Comment by caprice-j** [comment]
Okay, at least for the v1.0 I'll focus working code.
